/**
 * @export
 * @enum {string}
 */
export enum AzureCloudRegion {
  AUSTRALIA_EAST = 'AUSTRALIA_EAST',
  AUSTRALIA_SOUTHEAST = 'AUSTRALIA_SOUTHEAST',
  EUROPE_NORTH = 'EUROPE_NORTH',
  EUROPE_WEST = 'EUROPE_WEST',
  GERMANY_WESTCENTRAL = 'GERMANY_WESTCENTRAL',
  UAE_NORTH = 'UAE_NORTH',
  US_EAST = 'US_EAST',
  US_WEST2 = 'US_WEST2'
}

export default AzureCloudRegion;

