/**
 * The attribute that should be checked
 * @export
 * @enum {string}
 */
export enum ConditionAttribute {
  HEIGHT = 'HEIGHT',
  WIDTH = 'WIDTH',
  BITRATE = 'BITRATE',
  FPS = 'FPS',
  ASPECTRATIO = 'ASPECTRATIO',
  INPUTSTREAM = 'INPUTSTREAM',
  LANGUAGE = 'LANGUAGE',
  CHANNELFORMAT = 'CHANNELFORMAT',
  CHANNELLAYOUT = 'CHANNELLAYOUT',
  STREAMCOUNT = 'STREAMCOUNT',
  AUDIOSTREAMCOUNT = 'AUDIOSTREAMCOUNT',
  VIDEOSTREAMCOUNT = 'VIDEOSTREAMCOUNT',
  DURATION = 'DURATION',
  ROTATION = 'ROTATION',
  CONNECTION_STATUS = 'CONNECTION_STATUS',
  CONNECTION_STATUS_JUST_CHANGED = 'CONNECTION_STATUS_JUST_CHANGED'
}

export default ConditionAttribute;

