/**
 * @export
 * @enum {string}
 */
export enum InputStreamType {
  INGEST = 'INGEST',
  CONCATENATION = 'CONCATENATION',
  TRIMMING_TIME_BASED = 'TRIMMING_TIME_BASED',
  TRIMMING_TIME_CODE_TRACK = 'TRIMMING_TIME_CODE_TRACK',
  TRIMMING_H264_PICTURE_TIMING = 'TRIMMING_H264_PICTURE_TIMING',
  SIDECAR_DOLBY_VISION_METADATA = 'SIDECAR_DOLBY_VISION_METADATA',
  AUDIO_MIX = 'AUDIO_MIX',
  FILE = 'FILE',
  CAPTION_CEA608 = 'CAPTION_CEA608',
  CAPTION_CEA708 = 'CAPTION_CEA708',
  DVB_TELETEXT = 'DVB_TELETEXT'
}

export default InputStreamType;

