/**
 * @export
 * @enum {string}
 */
export enum SceneType {
  LOGO_IDENT = 'LOGO_IDENT',
  OPENING_CREDITS = 'OPENING_CREDITS',
  RECAP = 'RECAP',
  PREVIEW_THIS_TITLE = 'PREVIEW_THIS_TITLE',
  PROMOTION_OTHER_TITLE = 'PROMOTION_OTHER_TITLE',
  BREAK_BUMPER = 'BREAK_BUMPER',
  END_CREDITS = 'END_CREDITS',
  ADS = 'ADS',
  MAIN_CONTENT = 'MAIN_CONTENT',
  UNKNOWN = 'UNKNOWN'
}

export default SceneType;

